#!/bin/bash -e
# https://github.com/jimeh/dotfiles/commit/3470b1632fff4e97426e41a4c20fbb385688b782

# Ensure that tmux windows are by default named after the shell, rather than
# full path to the shell binary.
shell=$(basename "$SHELL")

# If reattach-to-user-namespace is not available, just run the command.
if [ -n "$(command -v reattach-to-user-namespace)" ]; then
  reattach-to-user-namespace -l "$shell"
else
  exec "$shell"
fi
